/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  aux_sym_keycode_token1 = 2,
  anon_sym_GT = 3,
  sym__not_keycode = 4,
  anon_sym_COLON_PERCENT = 5,
  aux_sym__range_s_command_token1 = 6,
  aux_sym__vimgrep_token1 = 7,
  anon_sym_cmd = 8,
  anon_sym_Cmd = 9,
  anon_sym_CMD = 10,
  anon_sym_COLON = 11,
  aux_sym__first_command_token1 = 12,
  anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT = 13,
  anon_sym_BSLASH = 14,
  anon_sym_PIPE = 15,
  anon_sym_printf = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COMMA = 18,
  anon_sym_RPAREN = 19,
  anon_sym_SQUOTE = 20,
  sym_string_content = 21,
  sym_scope = 22,
  sym_identifier = 23,
  sym_comment = 24,
  sym__blank = 25,
  sym_map_side = 26,
  sym_keycode = 27,
  sym__range_s_command = 28,
  sym__vimgrep = 29,
  sym__cmd_rhs = 30,
  sym__colon_rhs = 31,
  sym__first_command = 32,
  sym__range = 33,
  sym_command = 34,
  sym_pipe = 35,
  sym_expression = 36,
  sym_printf = 37,
  sym_string = 38,
  sym__argument = 39,
  sym_scoped_identifier = 40,
  aux_sym_map_side_repeat1 = 41,
  aux_sym__cmd_rhs_repeat1 = 42,
  aux_sym_printf_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [aux_sym_keycode_token1] = "keycode_token1",
  [anon_sym_GT] = ">",
  [sym__not_keycode] = "_not_keycode",
  [anon_sym_COLON_PERCENT] = "command",
  [aux_sym__range_s_command_token1] = "command",
  [aux_sym__vimgrep_token1] = "command",
  [anon_sym_cmd] = "keycode",
  [anon_sym_Cmd] = "keycode",
  [anon_sym_CMD] = "keycode",
  [anon_sym_COLON] = ":",
  [aux_sym__first_command_token1] = "_first_command_token1",
  [anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT] = "'<,'>",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_PIPE] = "|",
  [anon_sym_printf] = "printf",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SQUOTE] = "'",
  [sym_string_content] = "string_content",
  [sym_scope] = "scope",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym__blank] = "_blank",
  [sym_map_side] = "map_side",
  [sym_keycode] = "keycode",
  [sym__range_s_command] = "_range_s_command",
  [sym__vimgrep] = "_vimgrep",
  [sym__cmd_rhs] = "_cmd_rhs",
  [sym__colon_rhs] = "_colon_rhs",
  [sym__first_command] = "command",
  [sym__range] = "_range",
  [sym_command] = "command",
  [sym_pipe] = "pipe",
  [sym_expression] = "expression",
  [sym_printf] = "printf",
  [sym_string] = "string",
  [sym__argument] = "_argument",
  [sym_scoped_identifier] = "scoped_identifier",
  [aux_sym_map_side_repeat1] = "map_side_repeat1",
  [aux_sym__cmd_rhs_repeat1] = "_cmd_rhs_repeat1",
  [aux_sym_printf_repeat1] = "printf_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_keycode_token1] = aux_sym_keycode_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__not_keycode] = sym__not_keycode,
  [anon_sym_COLON_PERCENT] = sym_command,
  [aux_sym__range_s_command_token1] = sym_command,
  [aux_sym__vimgrep_token1] = sym_command,
  [anon_sym_cmd] = sym_keycode,
  [anon_sym_Cmd] = sym_keycode,
  [anon_sym_CMD] = sym_keycode,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym__first_command_token1] = aux_sym__first_command_token1,
  [anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT] = anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_printf] = anon_sym_printf,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_scope] = sym_scope,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym__blank] = sym__blank,
  [sym_map_side] = sym_map_side,
  [sym_keycode] = sym_keycode,
  [sym__range_s_command] = sym__range_s_command,
  [sym__vimgrep] = sym__vimgrep,
  [sym__cmd_rhs] = sym__cmd_rhs,
  [sym__colon_rhs] = sym__colon_rhs,
  [sym__first_command] = sym_command,
  [sym__range] = sym__range,
  [sym_command] = sym_command,
  [sym_pipe] = sym_pipe,
  [sym_expression] = sym_expression,
  [sym_printf] = sym_printf,
  [sym_string] = sym_string,
  [sym__argument] = sym__argument,
  [sym_scoped_identifier] = sym_scoped_identifier,
  [aux_sym_map_side_repeat1] = aux_sym_map_side_repeat1,
  [aux_sym__cmd_rhs_repeat1] = aux_sym__cmd_rhs_repeat1,
  [aux_sym_printf_repeat1] = aux_sym_printf_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_keycode_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__not_keycode] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_PERCENT] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__range_s_command_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__vimgrep_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_cmd] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Cmd] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CMD] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__first_command_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_printf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__blank] = {
    .visible = false,
    .named = true,
  },
  [sym_map_side] = {
    .visible = true,
    .named = true,
  },
  [sym_keycode] = {
    .visible = true,
    .named = true,
  },
  [sym__range_s_command] = {
    .visible = false,
    .named = true,
  },
  [sym__vimgrep] = {
    .visible = false,
    .named = true,
  },
  [sym__cmd_rhs] = {
    .visible = false,
    .named = true,
  },
  [sym__colon_rhs] = {
    .visible = false,
    .named = true,
  },
  [sym__first_command] = {
    .visible = true,
    .named = true,
  },
  [sym__range] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_printf] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_scoped_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_map_side_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__cmd_rhs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_printf_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '"', 78,
        '\'', 65,
        '(', 62,
        ')', 64,
        ',', 63,
        ':', 52,
        '<', 26,
        '>', 35,
        'C', 12,
        '\\', 58,
        'c', 17,
        'p', 19,
        '|', 59,
        'g', 10,
        'l', 10,
        'v', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(78);
      if (lookahead == 's') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 27,
        'C', 29,
        'c', 32,
        '\n', 79,
        '\r', 79,
        '\t', 33,
        0x0b, 33,
        '\f', 33,
        ' ', 33,
      );
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '\'') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(56);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(56);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '\'') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == ',') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(57);
      END_STATE();
    case 12:
      if (lookahead == 'M') ADVANCE(70);
      if (lookahead == 'm') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'g') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'm') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(45);
      END_STATE();
    case 23:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(44);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '"', 78,
        ':', 52,
        '<', 26,
        'p', 39,
        '\n', 79,
        '\r', 79,
        '\t', 41,
        0x0b, 41,
        '\f', 41,
        ' ', 41,
      );
      if (lookahead != 0 &&
          lookahead != '(') ADVANCE(42);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == '>') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'D') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'M') ADVANCE(28);
      if (lookahead == 'm') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'd') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'd') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'm') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__not_keycode);
      if (lookahead == 'f') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__not_keycode);
      if (lookahead == 'i') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__not_keycode);
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__not_keycode);
      if (lookahead == 'r') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__not_keycode);
      if (lookahead == 't') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__not_keycode);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__not_keycode);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON_PERCENT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__range_s_command_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__vimgrep_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_cmd);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_cmd);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_Cmd);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_Cmd);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_CMD);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_CMD);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '%') ADVANCE(43);
      if (lookahead == 'v') ADVANCE(15);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym__first_command_token1);
      if (lookahead == '<') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym__first_command_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(56);
      if (lookahead == '<' ||
          lookahead == '\\' ||
          lookahead == '|') ADVANCE(78);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym__first_command_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym__first_command_token1);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_printf);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_printf);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\'') ADVANCE(78);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(68);
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_string_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_scope);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__blank);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 24},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 24},
  [5] = {.lex_state = 24},
  [6] = {.lex_state = 24},
  [7] = {.lex_state = 24},
  [8] = {.lex_state = 24},
  [9] = {.lex_state = 24},
  [10] = {.lex_state = 24},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COLON_PERCENT] = ACTIONS(1),
    [aux_sym__vimgrep_token1] = ACTIONS(1),
    [anon_sym_cmd] = ACTIONS(1),
    [anon_sym_Cmd] = ACTIONS(1),
    [anon_sym_CMD] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_printf] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_scope] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__blank] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_map_side] = STATE(43),
    [sym_keycode] = STATE(2),
    [sym__range_s_command] = STATE(2),
    [sym__vimgrep] = STATE(2),
    [sym__cmd_rhs] = STATE(2),
    [sym__colon_rhs] = STATE(2),
    [sym__first_command] = STATE(14),
    [sym_expression] = STATE(2),
    [sym_printf] = STATE(5),
    [aux_sym_map_side_repeat1] = STATE(2),
    [anon_sym_LT] = ACTIONS(5),
    [sym__not_keycode] = ACTIONS(7),
    [anon_sym_COLON_PERCENT] = ACTIONS(9),
    [aux_sym__vimgrep_token1] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_printf] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym__blank] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_COLON_PERCENT,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_printf,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym__not_keycode,
    ACTIONS(23), 1,
      aux_sym__vimgrep_token1,
    STATE(5), 1,
      sym_printf,
    STATE(14), 1,
      sym__first_command,
    STATE(3), 7,
      sym_keycode,
      sym__range_s_command,
      sym__vimgrep,
      sym__cmd_rhs,
      sym__colon_rhs,
      sym_expression,
      aux_sym_map_side_repeat1,
  [43] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_LT,
    ACTIONS(30), 1,
      sym__not_keycode,
    ACTIONS(33), 1,
      anon_sym_COLON_PERCENT,
    ACTIONS(36), 1,
      aux_sym__vimgrep_token1,
    ACTIONS(39), 1,
      anon_sym_COLON,
    ACTIONS(42), 1,
      anon_sym_printf,
    STATE(5), 1,
      sym_printf,
    STATE(14), 1,
      sym__first_command,
    STATE(3), 7,
      sym_keycode,
      sym__range_s_command,
      sym__vimgrep,
      sym__cmd_rhs,
      sym__colon_rhs,
      sym_expression,
      aux_sym_map_side_repeat1,
  [86] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(47), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(45), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [104] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(51), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(49), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [122] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(55), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(53), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [140] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(59), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [158] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(63), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(61), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [176] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(67), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(65), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [194] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(71), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [212] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(75), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [230] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(79), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [248] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__blank,
    ACTIONS(83), 3,
      sym__not_keycode,
      anon_sym_COLON,
      anon_sym_printf,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_COLON_PERCENT,
      aux_sym__vimgrep_token1,
  [266] = 7,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(87), 1,
      anon_sym_BSLASH,
    ACTIONS(89), 1,
      anon_sym_PIPE,
    STATE(6), 1,
      sym_keycode,
    STATE(15), 1,
      aux_sym__cmd_rhs_repeat1,
    STATE(31), 1,
      sym_pipe,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [289] = 7,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(87), 1,
      anon_sym_BSLASH,
    ACTIONS(89), 1,
      anon_sym_PIPE,
    STATE(11), 1,
      sym_keycode,
    STATE(18), 1,
      aux_sym__cmd_rhs_repeat1,
    STATE(31), 1,
      sym_pipe,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [312] = 7,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(87), 1,
      anon_sym_BSLASH,
    ACTIONS(89), 1,
      anon_sym_PIPE,
    STATE(13), 1,
      sym_keycode,
    STATE(18), 1,
      aux_sym__cmd_rhs_repeat1,
    STATE(31), 1,
      sym_pipe,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [335] = 7,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(87), 1,
      anon_sym_BSLASH,
    ACTIONS(89), 1,
      anon_sym_PIPE,
    STATE(9), 1,
      sym_keycode,
    STATE(16), 1,
      aux_sym__cmd_rhs_repeat1,
    STATE(31), 1,
      sym_pipe,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [358] = 6,
    ACTIONS(91), 1,
      anon_sym_LT,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    ACTIONS(96), 1,
      anon_sym_PIPE,
    STATE(18), 1,
      aux_sym__cmd_rhs_repeat1,
    STATE(31), 1,
      sym_pipe,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [378] = 3,
    ACTIONS(99), 1,
      aux_sym_keycode_token1,
    ACTIONS(17), 2,
      sym_comment,
      sym__blank,
    ACTIONS(101), 3,
      anon_sym_cmd,
      anon_sym_Cmd,
      anon_sym_CMD,
  [391] = 4,
    ACTIONS(103), 1,
      aux_sym__first_command_token1,
    ACTIONS(105), 1,
      anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT,
    STATE(44), 1,
      sym__range,
    ACTIONS(17), 2,
      sym_comment,
      sym__blank,
  [405] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
    ACTIONS(107), 3,
      anon_sym_LT,
      anon_sym_BSLASH,
      anon_sym_PIPE,
  [415] = 4,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    ACTIONS(111), 1,
      anon_sym_SQUOTE,
    STATE(28), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [429] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
    ACTIONS(113), 3,
      anon_sym_LT,
      anon_sym_BSLASH,
      anon_sym_PIPE,
  [439] = 3,
    ACTIONS(115), 1,
      sym_scope,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
    STATE(36), 2,
      sym__argument,
      sym_scoped_identifier,
  [451] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
    ACTIONS(91), 3,
      anon_sym_LT,
      anon_sym_BSLASH,
      anon_sym_PIPE,
  [461] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
    ACTIONS(117), 3,
      anon_sym_LT,
      anon_sym_BSLASH,
      anon_sym_PIPE,
  [471] = 4,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_printf_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [485] = 4,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      aux_sym_printf_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [499] = 4,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_printf_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [513] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
    ACTIONS(130), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [522] = 3,
    ACTIONS(132), 1,
      aux_sym__first_command_token1,
    STATE(25), 1,
      sym_command,
    ACTIONS(17), 2,
      sym_comment,
      sym__blank,
  [533] = 3,
    ACTIONS(132), 1,
      aux_sym__first_command_token1,
    STATE(17), 1,
      sym_command,
    ACTIONS(17), 2,
      sym_comment,
      sym__blank,
  [544] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [553] = 3,
    ACTIONS(136), 1,
      anon_sym_SQUOTE,
    ACTIONS(138), 1,
      sym_string_content,
    ACTIONS(17), 2,
      sym_comment,
      sym__blank,
  [564] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
    ACTIONS(140), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [573] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
    ACTIONS(128), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [582] = 2,
    ACTIONS(142), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [590] = 2,
    ACTIONS(144), 1,
      aux_sym__first_command_token1,
    ACTIONS(17), 2,
      sym_comment,
      sym__blank,
  [598] = 2,
    ACTIONS(146), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [606] = 2,
    ACTIONS(148), 1,
      aux_sym__range_s_command_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [614] = 2,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [622] = 2,
    ACTIONS(152), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [630] = 2,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [638] = 2,
    ACTIONS(156), 1,
      aux_sym__first_command_token1,
    ACTIONS(17), 2,
      sym_comment,
      sym__blank,
  [646] = 2,
    ACTIONS(99), 1,
      aux_sym_keycode_token1,
    ACTIONS(17), 2,
      sym_comment,
      sym__blank,
  [654] = 2,
    ACTIONS(158), 1,
      aux_sym__first_command_token1,
    ACTIONS(17), 2,
      sym_comment,
      sym__blank,
  [662] = 2,
    ACTIONS(160), 1,
      anon_sym_PIPE,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
  [670] = 2,
    ACTIONS(162), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym__blank,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 104,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 158,
  [SMALL_STATE(9)] = 176,
  [SMALL_STATE(10)] = 194,
  [SMALL_STATE(11)] = 212,
  [SMALL_STATE(12)] = 230,
  [SMALL_STATE(13)] = 248,
  [SMALL_STATE(14)] = 266,
  [SMALL_STATE(15)] = 289,
  [SMALL_STATE(16)] = 312,
  [SMALL_STATE(17)] = 335,
  [SMALL_STATE(18)] = 358,
  [SMALL_STATE(19)] = 378,
  [SMALL_STATE(20)] = 391,
  [SMALL_STATE(21)] = 405,
  [SMALL_STATE(22)] = 415,
  [SMALL_STATE(23)] = 429,
  [SMALL_STATE(24)] = 439,
  [SMALL_STATE(25)] = 451,
  [SMALL_STATE(26)] = 461,
  [SMALL_STATE(27)] = 471,
  [SMALL_STATE(28)] = 485,
  [SMALL_STATE(29)] = 499,
  [SMALL_STATE(30)] = 513,
  [SMALL_STATE(31)] = 522,
  [SMALL_STATE(32)] = 533,
  [SMALL_STATE(33)] = 544,
  [SMALL_STATE(34)] = 553,
  [SMALL_STATE(35)] = 564,
  [SMALL_STATE(36)] = 573,
  [SMALL_STATE(37)] = 582,
  [SMALL_STATE(38)] = 590,
  [SMALL_STATE(39)] = 598,
  [SMALL_STATE(40)] = 606,
  [SMALL_STATE(41)] = 614,
  [SMALL_STATE(42)] = 622,
  [SMALL_STATE(43)] = 630,
  [SMALL_STATE(44)] = 638,
  [SMALL_STATE(45)] = 646,
  [SMALL_STATE(46)] = 654,
  [SMALL_STATE(47)] = 662,
  [SMALL_STATE(48)] = 670,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_side, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__range_s_command, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__range_s_command, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__colon_rhs, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__colon_rhs, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keycode, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keycode, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_printf, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_printf, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_rhs, 5, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cmd_rhs, 5, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_printf, 5, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_printf, 5, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__colon_rhs, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__colon_rhs, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_printf, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_printf, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_rhs, 6, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cmd_rhs, 6, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__cmd_rhs_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd_rhs_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd_rhs_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__first_command, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__first_command, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_printf_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_printf_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_identifier, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [154] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vim_map_side(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "vim_map_side",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
