/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  aux_sym_keycode_token1 = 2,
  anon_sym_GT = 3,
  sym__not_keycode = 4,
  anon_sym_cmd = 5,
  anon_sym_Cmd = 6,
  anon_sym_CMD = 7,
  anon_sym_cr = 8,
  anon_sym_CR = 9,
  anon_sym_COLON = 10,
  aux_sym__first_command_token1 = 11,
  anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT = 12,
  anon_sym_BSLASH_PIPE = 13,
  sym_map_side = 14,
  sym_keycode = 15,
  sym__cmd_rhs = 16,
  sym__colon_rhs = 17,
  sym__first_command = 18,
  sym__range = 19,
  sym_command = 20,
  sym__pipe = 21,
  aux_sym_map_side_repeat1 = 22,
  aux_sym__cmd_rhs_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [aux_sym_keycode_token1] = "keycode_token1",
  [anon_sym_GT] = ">",
  [sym__not_keycode] = "_not_keycode",
  [anon_sym_cmd] = "keycode",
  [anon_sym_Cmd] = "keycode",
  [anon_sym_CMD] = "keycode",
  [anon_sym_cr] = "keycode",
  [anon_sym_CR] = "keycode",
  [anon_sym_COLON] = ":",
  [aux_sym__first_command_token1] = "_first_command_token1",
  [anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT] = "'<,'>",
  [anon_sym_BSLASH_PIPE] = "\\|",
  [sym_map_side] = "map_side",
  [sym_keycode] = "keycode",
  [sym__cmd_rhs] = "_cmd_rhs",
  [sym__colon_rhs] = "_colon_rhs",
  [sym__first_command] = "command",
  [sym__range] = "_range",
  [sym_command] = "command",
  [sym__pipe] = "_pipe",
  [aux_sym_map_side_repeat1] = "map_side_repeat1",
  [aux_sym__cmd_rhs_repeat1] = "_cmd_rhs_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_keycode_token1] = aux_sym_keycode_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__not_keycode] = sym__not_keycode,
  [anon_sym_cmd] = sym_keycode,
  [anon_sym_Cmd] = sym_keycode,
  [anon_sym_CMD] = sym_keycode,
  [anon_sym_cr] = sym_keycode,
  [anon_sym_CR] = sym_keycode,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym__first_command_token1] = aux_sym__first_command_token1,
  [anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT] = anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT,
  [anon_sym_BSLASH_PIPE] = anon_sym_BSLASH_PIPE,
  [sym_map_side] = sym_map_side,
  [sym_keycode] = sym_keycode,
  [sym__cmd_rhs] = sym__cmd_rhs,
  [sym__colon_rhs] = sym__colon_rhs,
  [sym__first_command] = sym_command,
  [sym__range] = sym__range,
  [sym_command] = sym_command,
  [sym__pipe] = sym__pipe,
  [aux_sym_map_side_repeat1] = aux_sym_map_side_repeat1,
  [aux_sym__cmd_rhs_repeat1] = aux_sym__cmd_rhs_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_keycode_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__not_keycode] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_cmd] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Cmd] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CMD] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_cr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__first_command_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_map_side] = {
    .visible = true,
    .named = true,
  },
  [sym_keycode] = {
    .visible = true,
    .named = true,
  },
  [sym__cmd_rhs] = {
    .visible = false,
    .named = true,
  },
  [sym__colon_rhs] = {
    .visible = false,
    .named = true,
  },
  [sym__first_command] = {
    .visible = true,
    .named = true,
  },
  [sym__range] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym__pipe] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_map_side_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__cmd_rhs_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == ':') ADVANCE(35);
      if (lookahead == '<') ADVANCE(16);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead == 'C') ADVANCE(9);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == 'c') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(39);
      END_STATE();
    case 3:
      if (lookahead == ',') ADVANCE(1);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(39);
      END_STATE();
    case 5:
      if (lookahead == '<') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == 'C') ADVANCE(19);
      if (lookahead == 'c') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'D') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'M') ADVANCE(8);
      if (lookahead == 'R') ADVANCE(34);
      if (lookahead == 'm') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(11);
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 13:
      if (lookahead == '|') ADVANCE(41);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == ':') ADVANCE(35);
      if (lookahead == '<') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'C') ADVANCE(19);
      if (lookahead == 'c') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'D') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'M') ADVANCE(18);
      if (lookahead == 'm') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'd') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'd') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead == 'm') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_keycode_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__not_keycode);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__not_keycode);
      if (lookahead != 0 &&
          lookahead != ':' &&
          lookahead != '<') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_cmd);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_cmd);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_Cmd);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_Cmd);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_CMD);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_CMD);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_cr);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_CR);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__first_command_token1);
      if (lookahead == '\'') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__first_command_token1);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__first_command_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__first_command_token1);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '|') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASH_PIPE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_cmd] = ACTIONS(1),
    [anon_sym_Cmd] = ACTIONS(1),
    [anon_sym_CMD] = ACTIONS(1),
    [anon_sym_cr] = ACTIONS(1),
    [anon_sym_CR] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT] = ACTIONS(1),
    [anon_sym_BSLASH_PIPE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_map_side] = STATE(24),
    [sym_keycode] = STATE(2),
    [sym__cmd_rhs] = STATE(2),
    [sym__colon_rhs] = STATE(2),
    [sym__first_command] = STATE(4),
    [aux_sym_map_side_repeat1] = STATE(2),
    [anon_sym_LT] = ACTIONS(3),
    [sym__not_keycode] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_COLON,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym__not_keycode,
    STATE(4), 1,
      sym__first_command,
    STATE(3), 4,
      sym_keycode,
      sym__cmd_rhs,
      sym__colon_rhs,
      aux_sym_map_side_repeat1,
  [22] = 6,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(18), 1,
      sym__not_keycode,
    ACTIONS(21), 1,
      anon_sym_COLON,
    STATE(4), 1,
      sym__first_command,
    STATE(3), 4,
      sym_keycode,
      sym__cmd_rhs,
      sym__colon_rhs,
      aux_sym_map_side_repeat1,
  [44] = 4,
    ACTIONS(24), 1,
      anon_sym_LT,
    ACTIONS(26), 1,
      aux_sym__first_command_token1,
    ACTIONS(28), 1,
      anon_sym_BSLASH_PIPE,
    STATE(5), 3,
      sym_command,
      sym__pipe,
      aux_sym__cmd_rhs_repeat1,
  [59] = 4,
    ACTIONS(26), 1,
      aux_sym__first_command_token1,
    ACTIONS(30), 1,
      anon_sym_LT,
    ACTIONS(32), 1,
      anon_sym_BSLASH_PIPE,
    STATE(6), 3,
      sym_command,
      sym__pipe,
      aux_sym__cmd_rhs_repeat1,
  [74] = 4,
    ACTIONS(34), 1,
      anon_sym_LT,
    ACTIONS(36), 1,
      aux_sym__first_command_token1,
    ACTIONS(39), 1,
      anon_sym_BSLASH_PIPE,
    STATE(6), 3,
      sym_command,
      sym__pipe,
      aux_sym__cmd_rhs_repeat1,
  [89] = 4,
    ACTIONS(26), 1,
      aux_sym__first_command_token1,
    ACTIONS(32), 1,
      anon_sym_BSLASH_PIPE,
    ACTIONS(42), 1,
      anon_sym_LT,
    STATE(6), 3,
      sym_command,
      sym__pipe,
      aux_sym__cmd_rhs_repeat1,
  [104] = 3,
    ACTIONS(26), 1,
      aux_sym__first_command_token1,
    ACTIONS(44), 1,
      anon_sym_BSLASH_PIPE,
    STATE(7), 3,
      sym_command,
      sym__pipe,
      aux_sym__cmd_rhs_repeat1,
  [116] = 2,
    ACTIONS(46), 1,
      aux_sym_keycode_token1,
    ACTIONS(48), 3,
      anon_sym_cmd,
      anon_sym_Cmd,
      anon_sym_CMD,
  [125] = 2,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      sym__not_keycode,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_COLON,
  [134] = 2,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      sym__not_keycode,
    ACTIONS(56), 2,
      anon_sym_LT,
      anon_sym_COLON,
  [143] = 2,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      sym__not_keycode,
    ACTIONS(60), 2,
      anon_sym_LT,
      anon_sym_COLON,
  [152] = 2,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      sym__not_keycode,
    ACTIONS(64), 2,
      anon_sym_LT,
      anon_sym_COLON,
  [161] = 3,
    ACTIONS(66), 1,
      aux_sym__first_command_token1,
    ACTIONS(68), 1,
      anon_sym_SQUOTE_LT_COMMA_SQUOTE_GT,
    STATE(22), 1,
      sym__range,
  [171] = 2,
    ACTIONS(72), 1,
      aux_sym__first_command_token1,
    ACTIONS(70), 2,
      anon_sym_LT,
      anon_sym_BSLASH_PIPE,
  [179] = 2,
    ACTIONS(76), 1,
      aux_sym__first_command_token1,
    ACTIONS(74), 2,
      anon_sym_LT,
      anon_sym_BSLASH_PIPE,
  [187] = 2,
    ACTIONS(80), 1,
      aux_sym__first_command_token1,
    ACTIONS(78), 2,
      anon_sym_LT,
      anon_sym_BSLASH_PIPE,
  [195] = 1,
    ACTIONS(82), 2,
      anon_sym_cr,
      anon_sym_CR,
  [200] = 1,
    ACTIONS(84), 2,
      anon_sym_cr,
      anon_sym_CR,
  [205] = 1,
    ACTIONS(86), 2,
      anon_sym_cr,
      anon_sym_CR,
  [210] = 1,
    ACTIONS(88), 1,
      anon_sym_GT,
  [214] = 1,
    ACTIONS(90), 1,
      aux_sym__first_command_token1,
  [218] = 1,
    ACTIONS(92), 1,
      anon_sym_GT,
  [222] = 1,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
  [226] = 1,
    ACTIONS(96), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 59,
  [SMALL_STATE(6)] = 74,
  [SMALL_STATE(7)] = 89,
  [SMALL_STATE(8)] = 104,
  [SMALL_STATE(9)] = 116,
  [SMALL_STATE(10)] = 125,
  [SMALL_STATE(11)] = 134,
  [SMALL_STATE(12)] = 143,
  [SMALL_STATE(13)] = 152,
  [SMALL_STATE(14)] = 161,
  [SMALL_STATE(15)] = 171,
  [SMALL_STATE(16)] = 179,
  [SMALL_STATE(17)] = 187,
  [SMALL_STATE(18)] = 195,
  [SMALL_STATE(19)] = 200,
  [SMALL_STATE(20)] = 205,
  [SMALL_STATE(21)] = 210,
  [SMALL_STATE(22)] = 214,
  [SMALL_STATE(23)] = 218,
  [SMALL_STATE(24)] = 222,
  [SMALL_STATE(25)] = 226,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_side, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_side_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [24] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__cmd_rhs_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd_rhs_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__cmd_rhs_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__colon_rhs, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__colon_rhs, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__colon_rhs, 4, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__colon_rhs, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keycode, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keycode, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cmd_rhs, 7, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cmd_rhs, 7, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__first_command, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__first_command, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__first_command, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__first_command, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vim_map_side(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "vim_map_side",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
