name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - .github/workflows/ci.yml
      - package.json
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - .github/workflows/ci.yml
      - package.json

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.9
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: ${{ runner.os == 'Linux' }}
          # FIX: until I figure out why this fails
          # test-rust: true
          # test-node: true
          # test-python: true
          # test-go: true
          # test-swift: true
