name: Publish packages

on:
  push:
    tags: ["v*"]

jobs:
  npm:
    if: github.repository == 'Hdoc1509/tree-sitter-vim-map-side'
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  crates:
    if: github.repository == 'Hdoc1509/tree-sitter-vim-map-side'
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}

  pypi:
    if: github.repository == 'Hdoc1509/tree-sitter-vim-map-side'
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}

  github:
    if: github.repository == 'Hdoc1509/tree-sitter-vim-map-side'
    permissions:
      attestations: write
      contents: write
      id-token: write
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      generate: true
      attestations: true
      release-body: |
        Please refer to [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
